using System;
using System.Collections.Generic;
using Realms;
// These Are all the Json Objects that are received from API 
// calls the json gets parsed into these objects
namespace ForestHomeAdventureGuide
{


	// The Folowing Code was Generated by http://json2csharp.com/# by pasting in the expected json

	// -- Login

	public class LoginLogin
	{
		public int StatusCode { get; set; }
		public string StatusMessage { get; set; }
		public string ApiToken { get; set; }
		public string CompanyAPIURL { get; set; }
		public int CompanyID { get; set; }
		public string CompanyName { get; set; }
		public string CompanyWebsiteURL { get; set; }
		public int EntityID { get; set; }
		public string FirstName { get; set; }
		public bool IsAuthentic { get; set; }
		public string LastName { get; set; }
		public List<string> FamilyIDs { get; set; }
		public List<FamilyMember> FamilyMembers { get; set; }
		public List<Itinerary> Itineraries { get; set; }
	}
	// --- End Login 
	//-----Updating FamilyMembers and Itineraries 


	public class UpdateUpdate
	{
		public List<string> FamilyIDs { get; set; }
		public List<FamilyMember> FamilyMembers { get; set; }
		public List<Itinerary> Itineraries { get; set; }
		public string StatusMessage { get; set; }
	}
	// ----End Updating FamilyMembers and Itineraries 


	public class MediaLinkJson
	{
		public string StatusCode { get; set; }
		public string StatusMessage { get; set; }
		public List<LinkSummary> LinkSummaries { get; set; }
	}
	//---- End Media Links
	//----Scheduled Posts 


	public class ScheduledPostJson
	{
		public int StatusCode { get; set; }
		public string StatusMessage { get; set; }
		public List<ScheduledPost> Posts { get; set; }
	}
	// --- End Scheduled Posts
	// Blogs

	public class BlogResponse
	{
		public string status { get; set; }
		public List<Blog> blogs { get; set; }
	}
	// -- End Blogs

	//--- Camper Meds

	public class MedRecordJson
	{
		public string StatusCode { get; set; }
		public string StatusMessage { get; set; }
		public int RecordsCount { get; set; }
		public List<MedRecord> Records { get; set; }
	}
	// -- End Camper Meds

	// StoreCardBalances
	public class StoreCardBalanceJson
	{
		public int StatusCode { get; set; }
		public string StatusMessage { get; set; }
		public List<List<StoreCard>> Results { get; set; }
	}
    //
	// Weather
	public class Currently
	{
		public int time { get; set; }
		public string summary { get; set; }
		public string icon { get; set; }
		public int nearestStormDistance { get; set; }
		public int nearestStormBearing { get; set; }
		public int precipIntensity { get; set; }
		public int precipProbability { get; set; }
		public double temperature { get; set; }
		public double apparentTemperature { get; set; }
		public double dewPoint { get; set; }
		public double humidity { get; set; }
		public double windSpeed { get; set; }
		public int windBearing { get; set; }
		public int visibility { get; set; }
		public double cloudCover { get; set; }
		public double pressure { get; set; }
		public double ozone { get; set; }
	}

	public class MinutelyData
	{
		public int time { get; set; }
		public int precipIntensity { get; set; }
		public int precipProbability { get; set; }
	}

	public class Minutely
	{
		public string summary { get; set; }
		public string icon { get; set; }
		public List<MinutelyData> data { get; set; }
	}

	public class HourlyData
	{
		public int time { get; set; }
		public string summary { get; set; }
		public string icon { get; set; }
		public int precipIntensity { get; set; }
		public int precipProbability { get; set; }
		public double temperature { get; set; }
		public double apparentTemperature { get; set; }
		public double dewPoint { get; set; }
		public double humidity { get; set; }
		public double windSpeed { get; set; }
		public int windBearing { get; set; }
		public int visibility { get; set; }
		public double cloudCover { get; set; }
		public double pressure { get; set; }
		public double ozone { get; set; }
	}

	public class Hourly
	{
		public string summary { get; set; }
		public string icon { get; set; }
		public List<HourlyData> data { get; set; }
	}

	public class DailyData
	{
		public int time { get; set; }
		public string summary { get; set; }
		public string icon { get; set; }
		public int sunriseTime { get; set; }
		public int sunsetTime { get; set; }
		public double moonPhase { get; set; }
		public int precipIntensity { get; set; }
		public int precipIntensityMax { get; set; }
		public int precipProbability { get; set; }
		public double temperatureMin { get; set; }
		public int temperatureMinTime { get; set; }
		public double temperatureMax { get; set; }
		public int temperatureMaxTime { get; set; }
		public double apparentTemperatureMin { get; set; }
		public int apparentTemperatureMinTime { get; set; }
		public double apparentTemperatureMax { get; set; }
		public int apparentTemperatureMaxTime { get; set; }
		public double dewPoint { get; set; }
		public double humidity { get; set; }
		public double windSpeed { get; set; }
		public int windBearing { get; set; }
		public int visibility { get; set; }
		public double cloudCover { get; set; }
		public double pressure { get; set; }
		public double ozone { get; set; }
	}

	public class Daily
	{
		public string summary { get; set; }
		public string icon { get; set; }
		public List<DailyData> data { get; set; }
	}

	public class DarkSkyWeather
	{
		public double latitude { get; set; }
		public double longitude { get; set; }
		public string timezone { get; set; }
		public int offset { get; set; }
		public Currently currently { get; set; }
		public Minutely minutely { get; set; }
		public Hourly hourly { get; set; }
		public Daily daily { get; set; }
	}

	// End Weather
}
