# Uncomment this line to define a global platform for your project
platform :ios, ’10.0’

target 'FohoApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FohoApp
pod 'Kingfisher', '~> 3.0'
pod 'Splitflap', '~> 2.0.0’
pod 'YTVimeoExtractor', '~> 1.1’
pod 'PDFReader'
pod 'SwiftyJSON’
pod 'Flurry-iOS-SDK/FlurrySDK' #Analytics Pod

  target 'FohoAppTests' do
    inherit! :search_paths
    # Pods for testing
    
  end

  target 'FohoAppUITests' do
    inherit! :search_paths
    # Pods for testing
    
  end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end

end

